### ISSUE TITLE
Contactgegevens aanpassen werkt niet door landcode

### ISSUE THREAD

**Issue by dqos** [VersioAPI/Versio-WHMCS#2]
WHMCS heeft tegenwoordig een optie waardoor het automatisch landcodes beheert bij telefoonnummers. De Versio API accepteert alleen nummers zonder landcode, maar de module stuurt ze MET landcode waardoor je een error krijgt. Klanten kunnen dus nu geen contactgegevens aanpassen.

De fout zit hier:
https://github.com/VersioAPI/Versio-WHMCS/blob/51eb4c8527f935eac37f3e097c7a85e5482061ef/modules/registrars/versio/versio.php#L436

Ik heb het opgelost door de landcode te strippen en een 0 ervoor te plakken voordat het naar de API gestuurd wordt:
```
$contactDetails['phone'] = '0'.substr(strrchr($params['contactdetails']['Registrant']['Phone Number'], '.'), 1);
```

Willen jullie de module beter testen voor release? Graag DNSSEC beheer toevoegen.

**Comment by boonit** [comment]
@qarizma Je dient hiervoor de volgende instelling binnen WHMCS te wijzigen.
( onder algemene instellingen -> localisatie ) https://i.imgur.com/S5TbZrN.png

DNSSec ondersteuning staat zover ik weet niet op de planning. Je kunt uiteraard zelf toevoegingen maken ;)

**Comment by dqos** [comment]
@boonit Die functionaliteit is er met een reden ingebouwd, dus die laat ik liever staan. Overigens werkt het dan nog steeds niet voor bestaande klanten/gegevens. Mijn fix werkt voorlopig nog wel en is een kleine moeite om dit soort dingen op te vangen voordat je het naar de API post.

Over je laatste opmerking, het lijkt me logisch dat dat een taak voor Versio is. Maargoed ik zal voor _mijn_ klanten kijken of ik het kan implementeren.
